[build]
target = "aarch64-unknown-linux-gnu"

[env]
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=/Users/anatawa12/RustroverProjects/piterphone-pi-rs/qemu/sysroot"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
